services:
  # 1. BASE DE DATOS (Contenedorizada)
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ESPIrilo897
    ports:
      - "1444:1433"
    networks:
      - app-network

  # 2. API .NET (Auth)
  dotnet-api:
    build:
      context: ./AuthService
      dockerfile: AuthService.Api/Dockerfile
    container_name: dotnet_api_container
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PruebaPos;User Id=sa;Password=ESPIrilo897;TrustServerCertificate=True;
      - Jwt__Secret=u28snf82h2hd8291ns8d9172ms8jd82h
      - Jwt__Issuer=https://ghaz.com.ec/
    depends_on:
      - sqlserver
    networks:
      - app-network

  # 3. API PHP (Clientes/Pedidos)
  php-app:
    build:
      context: ./customer-order-service
      dockerfile: Dockerfile
    container_name: php_app_container
    volumes:
      - ./customer-order-service:/var/www
    environment:
      - DB_CONNECTION=sqlsrv
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - DB_DATABASE=PruebaPos
      - DB_USERNAME=sa
      - DB_PASSWORD=ESPIrilo897
      - JWT_SECRET=u28snf82h2hd8291ns8d9172ms8jd82h
    depends_on:
      - sqlserver
    networks:
      - app-network

  # 4. Servidor Web Nginx (Para PHP)
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "8000:80" # Acceso en http://localhost:8000
    volumes:
      - ./customer-order-service:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge